conn bsdpw-lab-proxy
    left={{ aws_public_ip }}
    leftsubnet={{ aws_private_ip_subnet }}
    leftfirewall=yes
    right={{ lab_public_ip }}
    rightsubnet={{ lab_cidr }}
    rightfirewall=yes
    keyexchange=ikev2
    ikelifetime=24h
    authby=psk
    auto=start
    ike=aes256-sha256-modp2048
    esp=aes256-sha384-modp2048
    lifetime=3600s
    mobike=no
    compress=yes
