connections {
  lab-tunnel {
    local_addrs  = {{ aws_public_ip | quote }}
    remote_addrs = {{ lab_public_ip | quote }}

    proposals = aes256-sha256-modp2048

    version = 2
    reauth_time = 0

    local {
      auth = psk
      id = {{ aws_public_ip | quote }}
    }
    remote {
      auth = psk
      id = {{ lab_public_ip | quote }}
    }

    children {
      net-net {
        local_ts  = {{ aws_private_ip_subnet | quote }}
        remote_ts = {{ lab_cidr | quote }}
        esp_proposals = aes256-sha256-modp2048
        start_action = start
        close_action = trap
      }
    }
  }
}

authorities {
  psk {
    # PSK referenced via secrets; ensure group_vars/all/secrets has ipsec_secret set
  }
}
