# High-level instructions for which tasks apply to which hosts
- name: apply local configuration to servers listed in hosts
  hosts: all
  roles:
    - os-detection   # bootstraps Python and detects OS; must run first
    - ipsec
  become_method: su
